# Where things are stored
source: .
destination: ./_site
layouts_dir: _layouts
includes_dir: _includes
data_dir: _data

# Handling Reading
safe: false
keep_files: [".git", ".svn"]
encoding: UTF-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
include:
  - _pages
  - _posts

exclude:
  - "_site"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - ".bundle/"
  - "tmp/"
  - "_drafts"

# Markdown Processing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Permalinks
permalink: pretty
paginate: 3

# Setup
title: "Maintenance Scripts"
tagline: "ITAdmin PowerShell Maintenance Scripts"
description: "A repository of PowerShell Scripts to automate a variety of IT related maintenance tasks."
baseurl: "/"

author:
  name: "Luke Leigh"
  email: me@lukeleigh.com

linkedin_username: lukeleigh

plugins:
  - rouge
  - github-pages
  - github-embed
  - jekyll-algolia
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-json-feed
  - jekyll-paginate
  - jekyll-sitemap

github: [metadata]
github_username: BanterBoy
repository: scripts-blog/BanterBoy.github.io

# Custom vars
version: 1.1.2
