# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Permalinks
paginate: 2
timezone: GB

# Setup
title: 'Maintenance Scripts'
tagline: 'ITAdmin PowerShell Maintenance Scripts'
description: 'Repository of Maintenance Scripts for a variety of tasks.'
url: https://scripts.lukeleigh.com
baseurl: /

author:
  name: 'Luke Leigh'
  url: https://www.linkedin.com/in/lukeleigh/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - [vendor]

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-json-feed
  - jekyll-algolia

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

github: [metadata]
repo: https://github.com/BanterBoy/hyde-theme

# Custom vars
version: 2.1.0
