# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Maintenance Scripts
tagline: 'Repository of Maintenance Scripts for a variety of tasks.'
description: ' '
url: https://scripts.lukeleigh.com
baseurl: /

author:
  name: 'Luke Leigh'
  url: https://www.linkedin.com/in/lukeleigh/
  
paginate: 5

# Custom vars
version: 2.1.0

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - [vendor]

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-json-feed
  - jekyll-algolia

github: [metadata]
