# Markdown Processing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Permalinks
permalink: pretty
paginate: 3

# Setup
title: "Maintenance Scripts"
tagline: "ITAdmin PowerShell Maintenance Scripts"
description: "A repository of PowerShell Scripts to automate a variety of IT related maintenance tasks."
baseurl: "/"

author:
  name: "Luke Leigh"
  email: me@lukeleigh.com

linkedin_username: lukeleigh

include:
  - _pages
  - _posts

exclude:
  - [Gemfile]
  - Gemfile
  - Gemfile.lock
  - node_modules
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - [vendor]

plugins:
  - rouge
  - github-pages
  - github-embed
  - jekyll-algolia
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-json-feed
  - jekyll-paginate
  - jekyll-sitemap

github: [metadata]
github_username: BanterBoy
repository: scripts-blog/BanterBoy.github.io

# Custom vars
version: 1.1.2
