# Dependencies
markdown: kramdown
highlighter: rouge
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Permalinks
paginate: 4
timezone: GB

# Setup
title: 'Maintenance Scripts'
tagline: 'ITAdmin PowerShell Maintenance Scripts'
description: 'A repository of PowerShell Scripts to automate a variety of maintenance tasks.'
url: https://scripts.lukeleigh.com
baseurl: /

author:
  name: 'Luke Leigh'
  url: https://www.linkedin.com/in/lukeleigh/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - [vendor]

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-json-feed
  - jekyll-algolia


github: [metadata]

github:
  repo: https://github.com/BanterBoy/maintenance

# Custom vars
version: 1.0.1
